---
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    assignees:
      - 'ruslankuzyshyn'
    reviewers:
      - 'ruslankuzyshyn'
